In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('stocks.xlsx', header = [0,1])
df

  Unnamed: 0_level_0    Price                  Price to earnings ratio (P/E)  \
             Company Facebook Google Microsoft                      Facebook
0         2017-06-05      155    955        66                         37.10
1         2017-06-06      150    987        69                         36.98
2         2017-06-07      153    963        62                         36.78
3         2017-06-08      155   1000        61                         36.11
4         2017-06-09      156   1012        66                         37.07


  Google Microsoft
0   32.0     30.31
1   31.3     30.56
2   31.7     30.46
3   31.2     30.11
4   30.0     31.00

In [8]:
df_stacked = df.stack()

C:\Users\USER\AppData\Local\Temp\ipykernel_7984\3205536143.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df_stacked = df.stack()

In [9]:
df.stack(level = 0)

C:\Users\USER\AppData\Local\Temp\ipykernel_7984\4254682145.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df.stack(level = 0)

                                   Company  Facebook  Google  Microsoft
0 Price                                NaT    155.00   955.0      66.00
  Price to earnings ratio (P/E)        NaT     37.10    32.0      30.31
  Unnamed: 0_level_0            2017-06-05       NaN     NaN        NaN
1 Price                                NaT    150.00   987.0      69.00
  Price to earnings ratio (P/E)        NaT     36.98    31.3      30.56
  Unnamed: 0_level_0            2017-06-06       NaN     NaN        NaN
2 Price                                NaT    153.00   963.0      62.00
  Price to earnings ratio (P/E)        NaT     36.78    31.7      30.46
  Unnamed: 0_level_0            2017-06-07       NaN     NaN        NaN
3 Price                                NaT    155.00  1000.0      61.00
  Price to earnings ratio (P/E)        NaT     36.11    31.2      30.11
  Unnamed: 0_level_0            2017-06-08       NaN     NaN        NaN
4 Price                                NaT    156.00  1012.0      66.00
  Price to earnings ratio (P/E)        NaT     37.07    30.0      31.00
  Unnamed: 0_level_0            2017-06-09       NaN     NaN        NaN

In [10]:
df_stacked.unstack()

  Unnamed: 0_level_0                             Price                   \
             Company Facebook Google Microsoft Company Facebook  Google
0         2017-06-05      NaT    NaT       NaT     NaN    155.0   955.0
1         2017-06-06      NaT    NaT       NaT     NaN    150.0   987.0
2         2017-06-07      NaT    NaT       NaT     NaN    153.0   963.0
3         2017-06-08      NaT    NaT       NaT     NaN    155.0  1000.0
4         2017-06-09      NaT    NaT       NaT     NaN    156.0  1012.0

            Price to earnings ratio (P/E)
  Microsoft                       Company Facebook Google Microsoft
0      66.0                           NaN    37.10   32.0     30.31
1      69.0                           NaN    36.98   31.3     30.56
2      62.0                           NaN    36.78   31.7     30.46
3      61.0                           NaN    36.11   31.2     30.11
4      66.0                           NaN    37.07   30.0     31.00

In [13]:
df2 = pd.read_excel('stocks_3_levels.xlsx', header = [0,1])
df2

  Unnamed: 0_level_0 Price Ratios                     \
  Unnamed: 0_level_1        Price Price.1    Price.2
0            Company     Facebook  Google  Microsoft
1            Q1 2016          155     955         66
2            Q2 2016          150     987         69
3            Q3 2016          153     963         62
4            Q4 2016          155    1000         61
5            Q1 2017          156    1012         66

                                                                 \
  Price to earnings ratio (P/E) Price to earnings ratio (P/E).1
0                      Facebook                          Google
1                          37.1                              32
2                         36.98                            31.3
3                         36.78                            31.7
4                         36.11                            31.2
5                         37.07                              30

                                  Income Statement                          \
  Price to earnings ratio (P/E).2        Net Sales Net Sales.1 Net Sales.2
0                       Microsoft         Facebook      Google   Microsoft
1                           30.31              2.6          20        18.7
2                           30.56              3.1          22        21.3
3                           30.46              4.3          24       21.45
4                           30.11              6.7          26       21.88
5                              31              8.1          31       22.34


  Net Profit Net Profit.1 Net Profit.2
0   Facebook       Google    Microsoft
1        0.8         5.43         4.56
2       0.97         5.89          5.1
3        1.2          6.1         5.43
4       1.67          6.5         5.89
5       2.03          6.4         6.09

In [15]:
df2.stack(level = 0)

C:\Users\USER\AppData\Local\Temp\ipykernel_7984\2500371938.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df2.stack(level = 0)

                     Unnamed: 0_level_1     Price Price.1    Price.2  \
0 Income Statement                  NaN       NaN     NaN        NaN
  Price Ratios                      NaN  Facebook  Google  Microsoft
  Unnamed: 0_level_0            Company       NaN     NaN        NaN
1 Income Statement                  NaN       NaN     NaN        NaN
  Price Ratios                      NaN       155     955         66
  Unnamed: 0_level_0            Q1 2016       NaN     NaN        NaN
2 Income Statement                  NaN       NaN     NaN        NaN
  Price Ratios                      NaN       150     987         69
  Unnamed: 0_level_0            Q2 2016       NaN     NaN        NaN
3 Income Statement                  NaN       NaN     NaN        NaN
  Price Ratios                      NaN       153     963         62
  Unnamed: 0_level_0            Q3 2016       NaN     NaN        NaN
4 Income Statement                  NaN       NaN     NaN        NaN
  Price Ratios                      NaN       155    1000         61
  Unnamed: 0_level_0            Q4 2016       NaN     NaN        NaN
5 Income Statement                  NaN       NaN     NaN        NaN
  Price Ratios                      NaN       156    1012         66
  Unnamed: 0_level_0            Q1 2017       NaN     NaN        NaN

                     Price to earnings ratio (P/E)  \
0 Income Statement                             NaN
  Price Ratios                            Facebook
  Unnamed: 0_level_0                           NaN
1 Income Statement                             NaN
  Price Ratios                                37.1
  Unnamed: 0_level_0                           NaN
2 Income Statement                             NaN
  Price Ratios                               36.98
  Unnamed: 0_level_0                           NaN
3 Income Statement                             NaN
  Price Ratios                               36.78
  Unnamed: 0_level_0                           NaN
4 Income Statement                             NaN
  Price Ratios                               36.11
  Unnamed: 0_level_0                           NaN
5 Income Statement                             NaN
  Price Ratios                               37.07
  Unnamed: 0_level_0                           NaN

                     Price to earnings ratio (P/E).1  \
0 Income Statement                               NaN
  Price Ratios                                Google
  Unnamed: 0_level_0                             NaN
1 Income Statement                               NaN
  Price Ratios                                    32
  Unnamed: 0_level_0                             NaN
2 Income Statement                               NaN
  Price Ratios                                  31.3
  Unnamed: 0_level_0                             NaN
3 Income Statement                               NaN
  Price Ratios                                  31.7
  Unnamed: 0_level_0                             NaN
4 Income Statement                               NaN
  Price Ratios                                  31.2
  Unnamed: 0_level_0                             NaN
5 Income Statement                               NaN
  Price Ratios                                    30
  Unnamed: 0_level_0                             NaN

                     Price to earnings ratio (P/E).2 Net Sales Net Sales.1  \
0 Income Statement                               NaN  Facebook      Google
  Price Ratios                             Microsoft       NaN         NaN
  Unnamed: 0_level_0                             NaN       NaN         NaN
1 Income Statement                               NaN       2.6          20
  Price Ratios                                 30.31       NaN         NaN
  Unnamed: 0_level_0                             NaN       NaN         NaN
2 Income Statement                               NaN       3.1          22
  Price Ratios                                 30.56       NaN         NaN
  Unnamed: 0_level_0                             NaN       NaN         NaN
3 Income Statement                               NaN       4.3          24
  Price Ratios                                 30.46       NaN         NaN
  Unnamed: 0_level_0                             NaN       NaN         NaN
4 Income Statement                               NaN       6.7          26
  Price Ratios                                 30.11       NaN         NaN
  Unnamed: 0_level_0                             NaN       NaN         NaN
5 Income Statement                               NaN       8.1          31
  Price Ratios                                    31       NaN         NaN
  Unnamed: 0_level_0                             NaN       NaN         NaN

                     Net Sales.2 Net Profit Net Profit.1 Net Profit.2
0 Income Statement     Microsoft   Facebook       Google    Microsoft
  Price Ratios               NaN        NaN          NaN          NaN
  Unnamed: 0_level_0         NaN        NaN          NaN          NaN
1 Income Statement          18.7        0.8         5.43         4.56
  Price Ratios               NaN        NaN          NaN          NaN
  Unnamed: 0_level_0         NaN        NaN          NaN          NaN
2 Income Statement          21.3       0.97         5.89          5.1
  Price Ratios               NaN        NaN          NaN          NaN
  Unnamed: 0_level_0         NaN        NaN          NaN          NaN
3 Income Statement         21.45        1.2          6.1         5.43
  Price Ratios               NaN        NaN          NaN          NaN
  Unnamed: 0_level_0         NaN        NaN          NaN          NaN
4 Income Statement         21.88       1.67          6.5         5.89
  Price Ratios               NaN        NaN          NaN          NaN
  Unnamed: 0_level_0         NaN        NaN          NaN          NaN
5 Income Statement         22.34       2.03          6.4         6.09
  Price Ratios               NaN        NaN          NaN          NaN
  Unnamed: 0_level_0         NaN        NaN          NaN          NaN

In [16]:
df2.stack(level = 1)

C:\Users\USER\AppData\Local\Temp\ipykernel_7984\1587966785.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df2.stack(level = 1)

                                  Unnamed: 0_level_0 Price Ratios  \
0 Net Profit                                     NaN          NaN
  Net Profit.1                                   NaN          NaN
  Net Profit.2                                   NaN          NaN
  Net Sales                                      NaN          NaN
  Net Sales.1                                    NaN          NaN
...                                              ...          ...
5 Price to earnings ratio (P/E).1                NaN           30
  Price to earnings ratio (P/E).2                NaN           31
  Price.1                                        NaN         1012
  Price.2                                        NaN           66
  Unnamed: 0_level_1                         Q1 2017          NaN

                                  Income Statement
0 Net Profit                              Facebook
  Net Profit.1                              Google
  Net Profit.2                           Microsoft
  Net Sales                               Facebook
  Net Sales.1                               Google
...                                            ...
5 Price to earnings ratio (P/E).1              NaN
  Price to earnings ratio (P/E).2              NaN
  Price.1                                      NaN
  Price.2                                      NaN
  Unnamed: 0_level_1                           NaN

[78 rows x 3 columns]

In [ ]:
df.level =